### ISSUE TITLE
Clarification Needed on Data

### ISSUE THREAD

**Issue by yezhihe** [CSCvelocityGroup/private-repository#2]
Q: Would you please clarify the naming conventions of the column <File/Image name> and what Denotation and Kymograph mean. I understand we have discussed this during our first meeting, but I would like a written documentation. We apologize for any inconvenience.

**Comment by adm0301** [comment]
In the "TIRF mor1-1 actual speed values" file, row 2A-F, as follows:

2A: The file image/name: "130215-1-2B" = DATE-Seedling-Cell/Replicate
            -The first number is the date (sorry it's backward... day/month/year). 
            -The second number is the seedling I chose from the plate. In this case, it was the first seedling as it was the first number.
            -The last number/letter indicates the cell/replicate. So, it was the second cell I took an image of, and the 2nd (B) replicate of that cell I took an image of. The previous cell and replicates must not have been good (1A/2A).

**Comment by adm0301** [comment]
2B: "MT?" = If the line traced on CSC particle projection, when transferred to the microtubule image, was in a microtubule domain, or not.

**Comment by adm0301** [comment]
2C: "Denotation" = Which kymograph it is. Say that there have been 10 particle paths I've traced not in microtubule domains, I had to distinguish them all from one another by giving them increasing values from 1. Same with if it was in a Microtubule domain (those were denotated with a number and then a "m," such as "1M." 

Basically this denotes when I have opened a new kymograph from a new particle path.

**Comment by adm0301** [comment]
2D: "Kymograph" = relates how many lines I was able to assess the slope of in each kymograph.

So, in 2D, it says 1. This is because in Kymograph 1 (from "Denotation" column), there was only one line visible to assess the slope from. Thus, the next row, 3C/D, says 2 for "Denotation," because it was the 2nd kymograph I was able to find with a line to assess from the same image, and says 1 for "Kymograph" because there was also only 1 line to assess the slope of.
